import { Poppins } from "next/font/google";
import "./globals.css";
import DynamicNavbar from "@/components/helpers/DynamicNavbar";
import SmoothScrollProvider from "@/components/helpers/SmoothScrollProvider";
import ClientWrapper from "@/redux/ClientWrapper";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "sonner";
import { Suspense } from "react";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-Poppins",
});

export const metadata = {
  title: "gaadi9",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <AuthProvider>
        <ClientWrapper>
          <SmoothScrollProvider>
            <nav className=" sm:padding-x shadow-lg shadow-slate-100"> <DynamicNavbar /></nav>
            <Suspense>
            {children}
            </Suspense>
          </SmoothScrollProvider>
        </ClientWrapper>
        </AuthProvider>
      </body>
      <Toaster/>
    </html>
  );
}
