import { Poppins } from "next/font/google";
import "./globals.css";
import DynamicNavbar from "@/components/helpers/DynamicNavbar";
import SmoothScrollProvider from "@/components/helpers/SmoothScrollProvider";
import ClientWrapper from "@/redux/ClientWrapper";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-Poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClientWrapper>
          <SmoothScrollProvider>
            <nav className=" sm:padding-x shadow-lg shadow-slate-100"> <DynamicNavbar /></nav>
            {children}
          </SmoothScrollProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
